apiVersion: v1
kind: Template
labels:
  template: java-ocp-job-demo
metadata:
  name: java-ocp-job-demo
  annotations:
      description: Java OCP Job Demo
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: java-ocp-job-demo
  spec:
    replicas: 1  
    selector:
      deploymentconfig: java-ocp-job-demo
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: java-ocp-job-demo
      spec:
        containers:
        - name: java-ocp-job-demo
          image: javaocpjobdemo-img:latest
          imagePullPolicy: Always
          envFrom: 
          - configMapRef:
              name: java-job-demo-map
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
        restartPolicy: Always
        serviceAccount: deployer
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - java-ocp-job-demo
        from:
          kind: ImageStreamTag
          name: javaocpjobdemo-img:latest
      type: ImageChange    
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: javaocpjobdemo-img
    labels:
      app: javaocpjobdemo
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: carljmosca/java-ocp-job-demo
- apiVersion: v1
  kind: Service
  metadata:
    name: java-ocp-job-demo
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: java-ocp-job-demo
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: java-job-demo-map
  data:
    MASTER_URL: ${MASTER_URL}
    JAVA_OPTIONS: ${JAVA_OPTIONS}
    MAXIMUM_JOB_TIME_IN_SECONDS: ${MAXIMUM_JOB_TIME_IN_SECONDS}
    MAXIMUM_JOBS: ${MAXIMUM_JOBS}
    PAUSE_SECONDS: ${PAUSE_SECONDS}
    TOTAL_JOBS: ${TOTAL_JOBS}        
parameters:
- description: The name for the application.
  displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: javaocpjobdemo
  from: "[a-zA-Z0-9]"
- description: Java options
  displayName: Java options
  name: JAVA_OPTIONS
  value: "-Xmx512m"
  required: true
- description: OpenShift Master URL
  displayName: Master URL
  name: MASTER_URL
  required: true
  value: "https://console.starter-ca-central-1.openshift.com"
- description: Maximum number of jobs to run (0 for unlimited)
  displayName: Total jobs
  name: TOTAL_JOBS
  required: true
  value: "0"
- description: Time to pause in between job processing (in seconds)
  displayName: Pause
  name: PAUSE_SECONDS
  value: "20"
  required: true
- description: Maximum number of jobs to run at one time
  displayName: Maximum jobs        
  name: MAXIMUM_JOBS
  value: "3"
  required: true
- description: Maximum time for job completion (in seconds)
  displayName: Maximum job time
  name: MAXIMUM_JOB_TIME_IN_SECONDS
  value: "20"
  required: true

